[tool.poetry]
name = "bookstore"
version = "0.1.0"
description = ""
authors = ["jahlon <jahlon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
